server:
  port: 8080
spring:
  application:
    name: Users
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
management:
  endpoints:
    web:
      exposure:
        include:
          - health